@startuml

!theme black-n-white from https://raw.githubusercontent.com/SBen-IV/plantuml-black-n-white-theme/main/theme

skinparam sequenceMessageAlign center

Browser -> Server: HTTP POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
Server --> Browser: 201 Created

@enduml
